### ISSUE TITLE
Typo in git URL

### ISSUE THREAD

**Issue by StevenTCramer** [TimeWarpEngineering/timewarp-fixie#2]
![image](https://user-images.githubusercontent.com/357219/194256204-db0de68e-0e74-42b8-ba1b-003c51c74e1e.png)

Should be

https://github.com/TimeWarpEngineering/timewarp-fixie/

**Comment by kaustav202** [comment]
can I fix this @StevenTCramer ?

**Comment by StevenTCramer** [comment]
Sorry @kaustav202 @chan18 had assigned it and he was the one that asked me to create it for hacktoberfest :)
